# Cloud Build configuration for CS Intelligence System
# This file defines the CI/CD pipeline for building and deploying to Cloud Run

substitutions:
  _REGION: asia-northeast3
  _PROJECT_ID: ${PROJECT_ID}
  _DASHBOARD_API_SERVICE: cs-dashboard-api
  _INGEST_API_SERVICE: cs-ingest-api
  _WORKER_SERVICE: cs-worker
  _FRONTEND_SERVICE: cs-frontend
  _CLOUD_SQL_INSTANCE: cs-intelligence-db

steps:
  # ============================================
  # Build Dashboard API
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_DASHBOARD_API_SERVICE}:${COMMIT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_DASHBOARD_API_SERVICE}:latest'
      - '-f'
      - 'server-py/Dockerfile'
      - './server-py'
    id: 'build-dashboard-api'

  # ============================================
  # Build Ingest API
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_INGEST_API_SERVICE}:${COMMIT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_INGEST_API_SERVICE}:latest'
      - '-f'
      - 'server-py/Dockerfile'
      - './server-py'
    id: 'build-ingest-api'

  # ============================================
  # Build Worker
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_WORKER_SERVICE}:${COMMIT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_WORKER_SERVICE}:latest'
      - '-f'
      - 'server-py/Dockerfile.worker'
      - './server-py'
    id: 'build-worker'

  # ============================================
  # Build Frontend
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_FRONTEND_SERVICE}:${COMMIT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_FRONTEND_SERVICE}:latest'
      - '--build-arg'
      - 'VITE_API_URL=https://${_DASHBOARD_API_SERVICE}-${_PROJECT_ID}.${_REGION}.run.app'
      - '-f'
      - 'ChatLoggerWeb/Dockerfile'
      - './ChatLoggerWeb'
    id: 'build-frontend'
    waitFor: ['-']

  # ============================================
  # Push all images to Artifact Registry
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_DASHBOARD_API_SERVICE}']
    id: 'push-dashboard-api'
    waitFor: ['build-dashboard-api']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_INGEST_API_SERVICE}']
    id: 'push-ingest-api'
    waitFor: ['build-ingest-api']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_WORKER_SERVICE}']
    id: 'push-worker'
    waitFor: ['build-worker']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_FRONTEND_SERVICE}']
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # ============================================
  # Deploy to Cloud Run
  # ============================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_DASHBOARD_API_SERVICE}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_DASHBOARD_API_SERVICE}:${COMMIT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_PROJECT_ID}:${_REGION}:${_CLOUD_SQL_INSTANCE}'
      - '--set-secrets'
      - 'DATABASE_URL=cs-database-url:latest,JWT_SECRET=cs-jwt-secret:latest'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
    id: 'deploy-dashboard-api'
    waitFor: ['push-dashboard-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_INGEST_API_SERVICE}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_INGEST_API_SERVICE}:${COMMIT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_PROJECT_ID}:${_REGION}:${_CLOUD_SQL_INSTANCE}'
      - '--set-secrets'
      - 'DATABASE_URL=cs-database-url:latest,DEVICE_KEY=cs-device-key:latest'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '20'
    id: 'deploy-ingest-api'
    waitFor: ['push-ingest-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_WORKER_SERVICE}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_WORKER_SERVICE}:${COMMIT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_PROJECT_ID}:${_REGION}:${_CLOUD_SQL_INSTANCE}'
      - '--set-secrets'
      - 'DATABASE_URL=cs-database-url:latest,ANTHROPIC_API_KEY=anthropic-api-key:latest,SLACK_WEBHOOK_URL=slack-webhook-url:latest'
      - '--set-env-vars'
      - 'ANTHROPIC_MODEL_DEFAULT=claude-3-haiku-20240307,ANTHROPIC_MODEL_ESCALATE=claude-3-5-sonnet-20241022,SLA_THRESHOLD_MINUTES=20,DASHBOARD_URL=https://cs.motionlabs.kr'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '3'
    id: 'deploy-worker'
    waitFor: ['push-worker']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_FRONTEND_SERVICE}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_FRONTEND_SERVICE}:${COMMIT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
    id: 'deploy-frontend'
    waitFor: ['push-frontend', 'deploy-dashboard-api']

# Images to store in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_DASHBOARD_API_SERVICE}:${COMMIT_SHA}'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_INGEST_API_SERVICE}:${COMMIT_SHA}'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_WORKER_SERVICE}:${COMMIT_SHA}'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/cs-intelligence/${_FRONTEND_SERVICE}:${COMMIT_SHA}'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1800s'
